cars<-read.csv("E:/R/cars.csv", header=TRUE)
cars
View(cars)
cor(cars)
m1=lm(MPG~.,data=cars)
summary(m1)
model1=lm(MPG~HP,data=cars)
summary(model1)
m2=lm(MPG~HP+SP,data=cars)
summary(m2)
m3=lm(MPG~HP+SP+WT,data=cars)
summary(m3)
m4=lm(MPG~HP+SP+VOL,data=cars[-c(77,71,78),])
summary(m4)
influenceIndexPlot(m4)
influenceIndexPlot(m4)
predict(m4,interval=("conf"))
predict(m4,data.frame(HP=40,SP=100,VOL=90))

